---
version: 0.0.11
slug: lorawan_server
name: LoRaWAN Server
description: Addon to allow local LoRaWAN services on HASS
# ingress: true
# ingress_port: 8080
codenotary: codenotary@threatfax.com
arch:
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  1680/udp: 1680
  8080/tcp: 9080
  8443/tcp: 9443
ports_description:
  1680/udp: Data From port_forwarders
startup: services
backup: cold
boot: auto
homeassistant_api: true