---
version: 0.0.8
slug: lorawan_server
name: LoRaWAN Server
description: Addon to allow local LoRaWAN services on HASS
ingress: true
ingress_port: 8080
arch:
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  1680/udp: 1680
ports_description:
  1680/udp: Data From port_forwarders
startup: services
backup: cold
boot: auto
homeassistant_api: true