---
version: 0.0.3
slug: lorawamn-server
name: LoRaWAN Server
description: Addon to allow local LoRaWAN services on HASS
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ports:
  8080/tcp: 8080
  1680/udp: 1680
startup: application
boot: auto
homeassistant_api: true